### ISSUE TITLE
Strips code blocks no matter the environment.

### ISSUE THREAD

**Issue by adamk33n3r** [kudashevs/webpack-remove-code-blocks#1]
This is stripping the marked code no matter if in development or production. What's the point then?

**Comment by kudashevs** [comment]
Hello @adamk33n3r ,

What exactly are you referring to when you're saying "development or production"? Which environment? Which building stage?

**Comment by adamk33n3r** [comment]
The webpack config setting `mode`. Or `NODE_ENV` My code is being stripped out in development mode too.

**Comment by kudashevs** [comment]
> The webpack config setting `mode`. Or `NODE_ENV` My code is being stripped out in development mode too.

@adamk33n3r that's a very good point. Thank you for bring it up.

I've[ implemented it](https://github.com/kudashevs/webpack-remove-code-blocks/commit/ecc1a51ba3deeda2f5e20081e071e43f95f10608) and now it skips the `development` mode.
Could you please check on your project if this is what you wanted?

**Comment by adamk33n3r** [comment]
I will, thank you!

**Comment by kudashevs** [comment]
The requested functionality is implemented in [v0.9.0](https://github.com/kudashevs/webpack-remove-code-blocks/releases/tag/v0.9.0).

**Comment by adamk33n3r** [comment]
Sorry it took so long for me to get back to verifying this, but it looks like your changes ONLY looks at `NODE_ENV` and not the webpack config setting `mode`. Using your newest code, I have to add `--node-env development` to my build task. but then it will work. It would be nice if this also could look at the webpack mode setting. Here are the docs https://webpack.js.org/configuration/mode/ and you can see that the builtin DefinePlugin uses that config and sets `NODE_ENV`.

But otherwise, thanks! It's working in the meantime.

**Comment by kudashevs** [comment]
The support of webpack `mode` option was implemented in the [v0.10.0](https://github.com/kudashevs/webpack-remove-code-blocks/releases/tag/v0.10.0) release.
In a couple of days I plan to pulish a stable initial release. So, stay tuned.

**Comment by adamk33n3r** [comment]
FYI, the version in your package.json is still 0.1.6

**Comment by kudashevs** [comment]
@adamk33n3r Oh, I've forgotten to write here.

I made the decision not to publish a stable initial release, but create a [new plugin](https://github.com/kudashevs/strip-code-webpack-plugin).
The concept is the same, but it is faster and have some advanced features.
